split variable declaration and assignment
If you assign a variable like this, you will get the exit code from
'local', which is not what we want and a common bash fallpit.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -146,7 +146,8 @@ function download {
 function install_font {
 	local font="$1"
 	local archive="$SRC_DIR/$1.tar.xz"
-	local tempdir="$(mktemp -d)" || die "Could not create temporary directory."
+	local tempdir
+	tempdir="$(mktemp -d)" || die "Could not create temporary directory."
 
 	trap 'rm -rf "$tempdir"' RETURN
 
